"""add ordered and dated trip stops

Revision ID: 00fae9a72c8b
Revises: 41126d9a82bc
Create Date: 2026-09-30 19:00:44.829851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = '00fae9a72c8b'
down_revision: Union[str, None] = '41126d9a82bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_list_items', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.add_column('saved_list_items', sa.Column('planned_on', sa.Date(), nullable=True))
    op.execute(sa.text("""
        WITH ranked AS (
            SELECT id, row_number() OVER (PARTITION BY list_id ORDER BY created_at, id) - 1 AS ordinal
            FROM saved_list_items
        )
        UPDATE saved_list_items AS item SET position = ranked.ordinal FROM ranked WHERE item.id = ranked.id
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_list_items', 'planned_on')
    op.drop_column('saved_list_items', 'position')
    # ### end Alembic commands ###
