"""add_field_verifications_and_single_active_review

Revision ID: 03ceb2a3cea8
Revises: 4094edfce6d8
Create Date: 2026-09-20 15:12:41.655663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = '03ceb2a3cea8'
down_revision: Union[str, None] = '4094edfce6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Veri geçişi SQL'leri modül seviyesinde: `tests/test_migration_data_preservation.py`
# bunları (transaction içinde, sonunda ROLLBACK ile) gerçek DB'de doğrular.
DEDUPE_REVIEWS_SQL = """
UPDATE reviews SET is_active = false
WHERE id IN (
    SELECT id FROM (
        SELECT id, row_number() OVER (
            PARTITION BY spot_id, user_id ORDER BY created_at DESC, id DESC
        ) AS rn FROM reviews
    ) ranked WHERE ranked.rn > 1
)
"""

RECOMPUTE_ACTIVE_SUMMARY_SQL = """
UPDATE spots s SET
    average_rating = agg.avg_rating,
    review_count = agg.cnt
FROM (
    SELECT sp.id AS spot_id,
           ROUND(AVG(r.rating)::numeric, 2)::float AS avg_rating,
           COUNT(r.id) AS cnt
    FROM spots sp
    LEFT JOIN reviews r ON r.spot_id = sp.id AND r.is_active
    WHERE sp.id IN (SELECT DISTINCT spot_id FROM reviews WHERE NOT is_active)
    GROUP BY sp.id
) agg
WHERE s.id = agg.spot_id
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_field_verifications',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('check_in_id', sa.UUID(), nullable=True),
    sa.Column('field', sa.Enum('road_access', 'overnight', 'fresh_water', 'electricity', 'grey_water', 'black_water', name='verifiable_field'), nullable=False),
    sa.Column('answer', sa.Enum('working', 'not_working', 'allowed', 'not_allowed', 'passable', 'difficult', 'impassable', 'unknown', name='verification_answer'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spot_field_verifications_spot_current', 'spot_field_verifications', ['spot_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_spot_field_verifications_spot_id'), 'spot_field_verifications', ['spot_id'], unique=False)
    op.create_index(op.f('ix_spot_field_verifications_user_id'), 'spot_field_verifications', ['user_id'], unique=False)
    op.create_index('uq_spot_field_verifications_one_current', 'spot_field_verifications', ['spot_id', 'user_id', 'field'], unique=True, postgresql_where=sa.text('is_current IS true'))
    op.add_column('reviews', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # --- Mükerrer yorum geçişi (GÜVENLİ, VERİ SİLMEZ) -------------------------
    # Aynı (spot_id, user_id) için birden fazla yorum varsa EN YENİSİ (created_at,
    # eşitlikte id) aktif kalır; eskileri `is_active=false` olur - metin/puan/araç
    # anlık görüntüsü/tarih HİÇBİR ŞEYİ değişmez, sadece "geçmiş" işaretlenir.
    # Unique index bundan SONRA oluşturulmalı, yoksa mükerrer satırlarda patlar.
    op.execute(DEDUPE_REVIEWS_SQL)
    op.execute(RECOMPUTE_ACTIVE_SUMMARY_SQL)
    op.create_index('uq_reviews_one_active_per_user_spot', 'reviews', ['spot_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reviews_one_active_per_user_spot', table_name='reviews', postgresql_where=sa.text('is_active IS true'))
    # Pasif (geçmiş) yorumlar downgrade'de SİLİNMEZ - hepsi yeniden "normal" satır olur;
    # bu yüzden etkilenen spot'ların özeti TÜM yorumlardan yeniden hesaplanır.
    op.execute(
        """
        UPDATE spots s SET
            average_rating = agg.avg_rating,
            review_count = agg.cnt
        FROM (
            SELECT sp.id AS spot_id,
                   ROUND(AVG(r.rating)::numeric, 2)::float AS avg_rating,
                   COUNT(r.id) AS cnt
            FROM spots sp
            LEFT JOIN reviews r ON r.spot_id = sp.id
            WHERE sp.id IN (SELECT DISTINCT spot_id FROM reviews WHERE NOT is_active)
            GROUP BY sp.id
        ) agg
        WHERE s.id = agg.spot_id
        """
    )
    op.drop_column('reviews', 'is_active')
    op.drop_index('uq_spot_field_verifications_one_current', table_name='spot_field_verifications', postgresql_where=sa.text('is_current IS true'))
    op.drop_index(op.f('ix_spot_field_verifications_user_id'), table_name='spot_field_verifications')
    op.drop_index(op.f('ix_spot_field_verifications_spot_id'), table_name='spot_field_verifications')
    op.drop_index('ix_spot_field_verifications_spot_current', table_name='spot_field_verifications')
    op.drop_table('spot_field_verifications')
    # `drop_table` Postgres ENUM tiplerini otomatik silmez (bkz. add_vehicle_profiles).
    sa.Enum(name='verification_answer').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='verifiable_field').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
