"""add spot essential amenities and camping rules

Revision ID: 13c0faa836cf
Revises: 6f7a8b9c0d1e
Create Date: 2026-09-30 17:18:52.641674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = '13c0faa836cf'
down_revision: Union[str, None] = '6f7a8b9c0d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot_amenities', sa.Column('has_toilet', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('spot_amenities', sa.Column('has_trash_bins', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('spot_amenities', sa.Column('is_free', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('spot_amenities', sa.Column('price_description', sa.String(length=300), nullable=True))
    op.add_column('spot_amenities', sa.Column('camping_behavior_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot_amenities', 'camping_behavior_allowed')
    op.drop_column('spot_amenities', 'price_description')
    op.drop_column('spot_amenities', 'is_free')
    op.drop_column('spot_amenities', 'has_trash_bins')
    op.drop_column('spot_amenities', 'has_toilet')
    # ### end Alembic commands ###
