"""add_review_dimension_ratings_and_vehicle_snapshot

Revision ID: 4094edfce6d8
Revises: abba42fd3500
Create Date: 2026-09-19 14:55:20.584991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = '4094edfce6d8'
down_revision: Union[str, None] = 'abba42fd3500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('safety_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('quietness_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('road_access_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('ground_suitability_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('cleanliness_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('view_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('signal_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('vehicle_type_snapshot', sa.Enum('motorhome', 'campervan', 'travel_trailer', 'other', name='vehicle_type'), nullable=True))
    op.add_column('reviews', sa.Column('vehicle_length_m_snapshot', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate CHECK constraint'leri algılamıyor (compare_check_constraints
    # varsayılan kapalı) - modeldeki 7 CheckConstraint'i elle ekliyoruz.
    # NOT: `vehicle_type_snapshot` yukarıda `op.add_column` ile eklendi -
    # `add_column` (create_table'ın aksine) mevcut bir tabloya YENİ bir Enum
    # tipi eklerken CREATE TYPE üretmiyor; burada zaten `vehicle_profiles`
    # migration'ında oluşturulmuş `vehicle_type` tipi YENİDEN KULLANILIYOR,
    # bu yüzden CREATE TYPE çakışması yok (bkz. add_user_roles migration'ındaki
    # aynı not).
    for column in (
        'safety_rating', 'quietness_rating', 'road_access_rating',
        'ground_suitability_rating', 'cleanliness_rating', 'view_rating', 'signal_rating',
    ):
        op.create_check_constraint(
            f'ck_reviews_{column}_range',
            'reviews',
            f'{column} IS NULL OR ({column} >= 1 AND {column} <= 5)',
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for column in (
        'safety_rating', 'quietness_rating', 'road_access_rating',
        'ground_suitability_rating', 'cleanliness_rating', 'view_rating', 'signal_rating',
    ):
        op.drop_constraint(f'ck_reviews_{column}_range', 'reviews', type_='check')
    op.drop_column('reviews', 'vehicle_length_m_snapshot')
    op.drop_column('reviews', 'vehicle_type_snapshot')
    op.drop_column('reviews', 'signal_rating')
    op.drop_column('reviews', 'view_rating')
    op.drop_column('reviews', 'cleanliness_rating')
    op.drop_column('reviews', 'ground_suitability_rating')
    op.drop_column('reviews', 'road_access_rating')
    op.drop_column('reviews', 'quietness_rating')
    op.drop_column('reviews', 'safety_rating')
    # ### end Alembic commands ###
