"""add travel rules content reports and account lifecycle

Revision ID: 41126d9a82bc
Revises: 13c0faa836cf
Create Date: 2026-09-30 18:33:11.862205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41126d9a82bc'
down_revision: Union[str, None] = '13c0faa836cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic does not detect additions to native PostgreSQL enums.
    for value in ("toilet", "trash_bins", "price", "camping_behavior"):
        op.execute(sa.text(f"ALTER TYPE verifiable_field ADD VALUE IF NOT EXISTS '{value}'"))
    for value in ("free", "paid"):
        op.execute(sa.text(f"ALTER TYPE verification_answer ADD VALUE IF NOT EXISTS '{value}'"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_cache',
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('query')
    )
    op.create_table('request_quotas',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('account_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_account_tokens_user_id'), 'account_tokens', ['user_id'], unique=False)
    op.create_table('content_reports',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('target_kind', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_reports_spot_id'), 'content_reports', ['spot_id'], unique=False)
    op.create_index(op.f('ix_content_reports_state'), 'content_reports', ['state'], unique=False)
    op.create_index('uq_content_reports_pending', 'content_reports', ['reporter_id', 'target_kind', 'target_id', 'reason'], unique=True, postgresql_where=sa.text("state = 'pending'"))
    op.create_table('spot_changes',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_changes_spot_id'), 'spot_changes', ['spot_id'], unique=False)
    op.add_column('spot_amenities', sa.Column('rule_information_known', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('spot_photos', sa.Column('photo_kind', sa.String(length=20), server_default='general', nullable=False))
    op.add_column('spot_photos', sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('spots', sa.Column('overnight_status', sa.String(length=20), server_default='unknown', nullable=False))
    op.add_column('spots', sa.Column('max_stay_nights', sa.Integer(), nullable=True))
    op.add_column('spots', sa.Column('rule_description', sa.Text(), nullable=True))
    op.add_column('spots', sa.Column('rule_source', sa.String(length=300), nullable=True))
    op.add_column('spots', sa.Column('rule_checked_on', sa.Date(), nullable=True))
    op.add_column('spots', sa.Column('private_property_permission', sa.String(length=20), server_default='unknown', nullable=False))
    op.add_column('spots', sa.Column('entry_latitude', sa.Float(), nullable=True))
    op.add_column('spots', sa.Column('entry_longitude', sa.Float(), nullable=True))
    op.add_column('spots', sa.Column('approach_description', sa.Text(), nullable=True))
    op.add_column('spots', sa.Column('access_season', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('tokens_valid_after', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint("ck_spots_overnight_status", "spots", "overnight_status IN ('allowed','not_allowed','unknown')")
    op.create_check_constraint("ck_spots_property_permission", "spots", "private_property_permission IN ('required','not_required','unknown')")
    op.create_check_constraint("ck_spots_max_stay", "spots", "max_stay_nights IS NULL OR max_stay_nights BETWEEN 1 AND 365")
    op.create_check_constraint("ck_spots_entry_coordinates", "spots", "(entry_latitude IS NULL AND entry_longitude IS NULL) OR (entry_latitude BETWEEN -90 AND 90 AND entry_longitude BETWEEN -180 AND 180 AND entry_latitude IS NOT NULL AND entry_longitude IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Additional enum values are deliberately retained to preserve verification history.
    for name in ("ck_spots_entry_coordinates", "ck_spots_max_stay", "ck_spots_property_permission", "ck_spots_overnight_status"):
        op.drop_constraint(name, "spots", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens_valid_after')
    op.drop_column('users', 'email_verified')
    op.drop_column('spots', 'access_season')
    op.drop_column('spots', 'approach_description')
    op.drop_column('spots', 'entry_longitude')
    op.drop_column('spots', 'entry_latitude')
    op.drop_column('spots', 'private_property_permission')
    op.drop_column('spots', 'rule_checked_on')
    op.drop_column('spots', 'rule_source')
    op.drop_column('spots', 'rule_description')
    op.drop_column('spots', 'max_stay_nights')
    op.drop_column('spots', 'overnight_status')
    op.drop_column('spot_photos', 'is_hidden')
    op.drop_column('spot_photos', 'photo_kind')
    op.drop_column('spot_amenities', 'rule_information_known')
    op.drop_index(op.f('ix_spot_changes_spot_id'), table_name='spot_changes')
    op.drop_table('spot_changes')
    op.drop_index('uq_content_reports_pending', table_name='content_reports', postgresql_where=sa.text("state = 'pending'"))
    op.drop_index(op.f('ix_content_reports_state'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_spot_id'), table_name='content_reports')
    op.drop_table('content_reports')
    op.drop_index(op.f('ix_account_tokens_user_id'), table_name='account_tokens')
    op.drop_table('account_tokens')
    op.drop_table('request_quotas')
    op.drop_table('place_cache')
    # ### end Alembic commands ###
