"""add users.trust_score and spots.average_rating/review_count

Revision ID: 4c05855b8268
Revises: 8621cc9ec581
Create Date: 2026-09-06 13:17:22.528696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = '4c05855b8268'
down_revision: Union[str, None] = '8621cc9ec581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('average_rating', sa.Float(), nullable=True))
    # NOT NULL kolonlar için server_default eklendi: tabloda zaten satır var
    # (seed verisi), server_default olmadan bu ALTER "column contains null
    # values" hatasıyla patlardı. SQLAlchemy modelindeki `default=0` sadece
    # ORM INSERT'lerinde uygulanan Python-side bir default olduğu için
    # autogenerate bunu otomatik render etmez - elle eklendi.
    op.add_column(
        'spots',
        sa.Column('review_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'users',
        sa.Column('trust_score', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trust_score')
    op.drop_column('spots', 'review_count')
    op.drop_column('spots', 'average_rating')
    # ### end Alembic commands ###
