"""add_vehicle_profiles

Revision ID: 6eee36e968d8
Revises: fe936a864afe
Create Date: 2026-09-16 08:29:50.386674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = '6eee36e968d8'
down_revision: Union[str, None] = 'fe936a864afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


vehicle_type_enum = sa.Enum('motorhome', 'campervan', 'travel_trailer', 'other', name='vehicle_type')
vehicle_drivetrain_enum = sa.Enum('4x2', '4x4', name='vehicle_drivetrain')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.Enum('motorhome', 'campervan', 'travel_trailer', 'other', name='vehicle_type'), nullable=False),
    sa.Column('length_m', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('width_m', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('height_m', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('drivetrain', sa.Enum('4x2', '4x4', name='vehicle_drivetrain'), nullable=False),
    sa.Column('has_grey_water_tank', sa.Boolean(), nullable=False),
    sa.Column('has_black_water_cassette', sa.Boolean(), nullable=False),
    sa.Column('has_solar_power', sa.Boolean(), nullable=False),
    sa.Column('travels_with_pet', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height_m IS NULL OR (height_m > 0 AND height_m <= 5)', name='ck_vehicle_profiles_height_m_range'),
    sa.CheckConstraint('length_m > 0 AND length_m <= 30', name='ck_vehicle_profiles_length_m_range'),
    sa.CheckConstraint('weight_kg IS NULL OR (weight_kg > 0 AND weight_kg <= 10000)', name='ck_vehicle_profiles_weight_kg_range'),
    sa.CheckConstraint('width_m IS NULL OR (width_m > 0 AND width_m <= 6)', name='ck_vehicle_profiles_width_m_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_profiles_user_id'), 'vehicle_profiles', ['user_id'], unique=False)
    op.create_index('uq_vehicle_profiles_one_active_per_user', 'vehicle_profiles', ['user_id'], unique=True, postgresql_where=sa.text('is_active IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_vehicle_profiles_one_active_per_user', table_name='vehicle_profiles', postgresql_where=sa.text('is_active IS true'))
    op.drop_index(op.f('ix_vehicle_profiles_user_id'), table_name='vehicle_profiles')
    op.drop_table('vehicle_profiles')
    # ### end Alembic commands ###
    # `create_table` içindeki inline `sa.Enum(...)` CREATE TYPE'ı otomatik
    # tetikler (checkfirst) ama `drop_table` DROP TYPE'ı OTOMATİK YAPMAZ -
    # bu bilinen bir SQLAlchemy davranışı. Elle silmezsek downgrade sonrası
    # tekrar upgrade etmeye çalışmak "type already exists" ile patlar.
    vehicle_drivetrain_enum.drop(op.get_bind(), checkfirst=True)
    vehicle_type_enum.drop(op.get_bind(), checkfirst=True)
