"""initial schema: spots, passability, amenities, dynamic_status, reviews, photos, check_ins, users

Revision ID: 8621cc9ec581
Revises: 
Create Date: 2026-09-06 12:57:10.651871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8621cc9ec581'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('spots',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('wild_camping', 'campsite', 'sanistation_only', 'day_parking', 'farm_stay', name='spot_category'), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOT: 'idx_spots_coordinates' GiST index'i burada AYRICA create_index ile
    # açılmıyor - GeoAlchemy2, Geometry(spatial_index=True) sütunu için bunu
    # CREATE TABLE'a bağlı bir DDL event'i ile otomatik oluşturuyor; autogenerate
    # bunu ayrıca (duplicate) render ettiği için elle çıkarıldı. Bkz. GeoAlchemy2
    # resmi Alembic entegrasyon notları.
    op.create_index(op.f('ix_spots_category'), 'spots', ['category'], unique=False)
    op.create_index('ix_spots_category_verified', 'spots', ['category', 'is_verified'], unique=False)
    op.create_index(op.f('ix_spots_deleted_at'), 'spots', ['deleted_at'], unique=False)
    op.create_index('ix_spots_updated_at', 'spots', ['updated_at'], unique=False)
    op.create_table('check_ins',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('planned_nights', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_spot_id'), 'check_ins', ['spot_id'], unique=False)
    op.create_table('dynamic_status',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('police_intervention', sa.Enum('none', 'warning', 'fine', 'banned', 'unknown', name='police_intervention_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('crowd_level', sa.Enum('empty', 'low', 'medium', 'high', 'full', name='crowd_level'), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_status_spot_id'), 'dynamic_status', ['spot_id'], unique=False)
    op.create_table('reviews',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_spot_id'), 'reviews', ['spot_id'], unique=False)
    op.create_table('spot_amenities',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('fresh_water_thread', sa.Boolean(), nullable=False),
    sa.Column('black_water', sa.Boolean(), nullable=False),
    sa.Column('grey_water', sa.Boolean(), nullable=False),
    sa.Column('electricity_220v', sa.Boolean(), nullable=False),
    sa.Column('gsm_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spot_id')
    )
    op.create_table('spot_passability',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('road_type', sa.Enum('asphalt', 'gravel', 'dirt', 'rocky', name='road_type'), nullable=False),
    sa.Column('max_vehicle_length', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('clearance_required', sa.Enum('low', 'standard', 'high_4x4', name='clearance_required'), nullable=False),
    sa.Column('caravan_types_allowed', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('steep_incline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spot_id')
    )
    op.create_table('spot_photos',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('storage_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_photos_spot_id'), 'spot_photos', ['spot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spot_photos_spot_id'), table_name='spot_photos')
    op.drop_table('spot_photos')
    op.drop_table('spot_passability')
    op.drop_table('spot_amenities')
    op.drop_index(op.f('ix_reviews_spot_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_dynamic_status_spot_id'), table_name='dynamic_status')
    op.drop_table('dynamic_status')
    op.drop_index(op.f('ix_check_ins_spot_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index('ix_spots_updated_at', table_name='spots')
    op.drop_index(op.f('ix_spots_deleted_at'), table_name='spots')
    op.drop_index('ix_spots_category_verified', table_name='spots')
    op.drop_index(op.f('ix_spots_category'), table_name='spots')
    # idx_spots_coordinates ayrıca create edilmediği için burada da drop
    # edilmiyor; drop_table zaten tabloya bağlı tüm index'leri kaldırır.
    op.drop_table('spots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
