"""extend_spot_passability_vehicle_limits

Revision ID: abba42fd3500
Revises: 6eee36e968d8
Create Date: 2026-09-16 08:46:48.469425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = 'abba42fd3500'
down_revision: Union[str, None] = '6eee36e968d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot_passability', sa.Column('max_vehicle_width', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('spot_passability', sa.Column('max_vehicle_height', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('spot_passability', sa.Column('max_vehicle_weight_kg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate CHECK constraint'leri algılamıyor (compare_check_constraints
    # varsayılan kapalı) - modeldeki 3 CheckConstraint'i elle ekliyoruz.
    op.create_check_constraint(
        'ck_spot_passability_max_vehicle_width_range',
        'spot_passability',
        'max_vehicle_width IS NULL OR (max_vehicle_width > 0 AND max_vehicle_width <= 6)',
    )
    op.create_check_constraint(
        'ck_spot_passability_max_vehicle_height_range',
        'spot_passability',
        'max_vehicle_height IS NULL OR (max_vehicle_height > 0 AND max_vehicle_height <= 5)',
    )
    op.create_check_constraint(
        'ck_spot_passability_max_vehicle_weight_kg_range',
        'spot_passability',
        'max_vehicle_weight_kg IS NULL OR (max_vehicle_weight_kg > 0 AND max_vehicle_weight_kg <= 10000)',
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_spot_passability_max_vehicle_weight_kg_range', 'spot_passability', type_='check')
    op.drop_constraint('ck_spot_passability_max_vehicle_height_range', 'spot_passability', type_='check')
    op.drop_constraint('ck_spot_passability_max_vehicle_width_range', 'spot_passability', type_='check')
    op.drop_column('spot_passability', 'max_vehicle_weight_kg')
    op.drop_column('spot_passability', 'max_vehicle_height')
    op.drop_column('spot_passability', 'max_vehicle_width')
    # ### end Alembic commands ###
