"""add_user_roles

Revision ID: bd3e69277c58
Revises: 4c05855b8268
Create Date: 2026-09-06 18:02:11.483454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = 'bd3e69277c58'
down_revision: Union[str, None] = '4c05855b8268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_role_enum = sa.Enum('user', 'moderator', 'admin', name='user_role')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `op.add_column` (create_table'ın aksine) mevcut bir tabloya YENİ bir
    # Enum tipi eklerken CREATE TYPE'ı otomatik üretmiyor - bu bilinen bir
    # Alembic/PostgreSQL davranışı. Tipi elle, checkfirst=True ile
    # oluşturuyoruz (böylece migration'ı ikinci kez çalıştırmak da güvenli).
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # server_default eklendi: tabloda zaten kullanıcı satırı var (bkz. önceki
    # migration'lardaki review_count/trust_score notu) - server_default
    # olmadan bu ALTER "column contains null values" hatasıyla patlardı.
    op.add_column(
        'users',
        sa.Column('role', user_role_enum, nullable=False, server_default='user'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
