"""add_thumbnail_url_to_spot_photos

Revision ID: da93d3487d37
Revises: bd3e69277c58
Create Date: 2026-09-06 18:29:43.406806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = 'da93d3487d37'
down_revision: Union[str, None] = 'bd3e69277c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot_photos', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot_photos', 'thumbnail_url')
    # ### end Alembic commands ###
