"""add_saved_lists_and_items

Revision ID: fe936a864afe
Revises: da93d3487d37
Create Date: 2026-09-08 11:46:31.653686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401  -- autogenerate, Geometry sütunlarını bu modül üzerinden render eder


# revision identifiers, used by Alembic.
revision: str = 'fe936a864afe'
down_revision: Union[str, None] = 'da93d3487d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_lists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_default_favorites', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_lists_user_id'), 'saved_lists', ['user_id'], unique=False)
    op.create_index('uq_saved_lists_one_default_favorites_per_user', 'saved_lists', ['user_id'], unique=True, postgresql_where=sa.text('is_default_favorites IS true'))
    op.create_table('saved_list_items',
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['saved_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'spot_id', name='uq_saved_list_items_list_spot')
    )
    op.create_index(op.f('ix_saved_list_items_list_id'), 'saved_list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_saved_list_items_spot_id'), 'saved_list_items', ['spot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_list_items_spot_id'), table_name='saved_list_items')
    op.drop_index(op.f('ix_saved_list_items_list_id'), table_name='saved_list_items')
    op.drop_table('saved_list_items')
    op.drop_index('uq_saved_lists_one_default_favorites_per_user', table_name='saved_lists', postgresql_where=sa.text('is_default_favorites IS true'))
    op.drop_index(op.f('ix_saved_lists_user_id'), table_name='saved_lists')
    op.drop_table('saved_lists')
    # ### end Alembic commands ###
